### ISSUE TITLE
ToDo List Page Crashing

### ISSUE THREAD

**Issue by oniikabuto** [MadeBaruna/paimon-moe#346]
i understand from the pinned post that the todo list is being completely rehauled, but after the new update with the wanderer and faruzan being added in 3.3, i can't use my list at all. most of the time it won't even load the page at all, freezing the entire website in the process, however when it does load it won't show the summary, won't allow me to deduct items, delete characters from the list or move them. if this is because of maintenance i totally understand, but i thought i'd report the problem here for future reference. 
![todo list error](https://user-images.githubusercontent.com/120166988/206651703-6078a1a7-3089-473f-9225-2d5160d2a753.png)
![todo list page lag](https://user-images.githubusercontent.com/120166988/206651888-1b6196be-1961-42c5-ae33-921d6470d3bb.png)

**Comment by seangibbz** [comment]
After some digging, I believe that this bug is caused by improper handling of the Redcrest item for those who had Candace in their To-Do list.  Prior to Paimon.moe v3.3, the item was listed with the properties:
```
"id": "redcrest",
"name": "Redcrest"
```
However, this item had it's in-game name since changed and paimon.moe included this change along with their 3.3 update.
```
"id": "henna_berry",
"name": "Henna Berry",
```
The problem seems to be for users who had Candace in their to-do list, the website doesn't know how to handle the now-nonexistent `redcrest` item; the item in the user's cached data will not match the updated `henna_berry` id.

Until the issue is resolved, users should be able to fix the situation via the following steps:

1. From the paimon.moe Settings page, export your data as a JSON file.
2. Open the file in notepad or your text editor of choice.
3. Use the Find>Replace function and type in `redcrest` and replace with `henna_berry`
**Make sure you select "Match case"**
4. Replace All
5. Repeat steps 3-4 with `Redcrest` and `Henna Berry`
6. Save the newly edited file
7. Import your new file via the paimon.moe Settinga page

**Comment by oniikabuto** [comment]
Thank you for letting me know the issue, I really appreciate it! I’ll be sure to do that in a little bit, and I’ll inform you if the solution offered fixed the bug. As soon as I check and make sure, I’ll close this forum. I hope Hoyoverse doesn’t change item names again, because it would be really bothersome for something like this to happen to you guy again! Have a lovely day, and thank you again!

**Comment by oniikabuto** [comment]
I followed all of the steps listed above and it worked perfectly! Thank you very much for your assistance, and I hope this helps other users and devs in the future!
