### ISSUE TITLE
Site being flagged by Avast Antivirus

### ISSUE THREAD

**Issue by RaSan147** [MadeBaruna/paimon-moe#430]
kindly inform the AV company as False positive

**Comment by jogerj** [comment]
You can safely uninstall Avast or set exclusion rules

**Comment by ryanbenson** [comment]
Here's more information, at least when I'm getting this notification. It wasn't triggering this a couple of days ago. So something changed on the JS, or on Avast's end


![Screenshot 2023-07-06 085347](https://github.com/MadeBaruna/paimon-moe/assets/588599/4c42c2e4-b893-46a1-b1e4-3380516d5e02)
![Screenshot 2023-07-06 085403](https://github.com/MadeBaruna/paimon-moe/assets/588599/b6a8d583-2d89-480b-9065-f52854c6ba13)

**Comment by jogerj** [comment]
@ryanbenson 

This scanner just flags whatever ends with *.js as suspicious. It doesn't even bother fetching the actual content of the URL. It isn't helpful at all.

![Screenshot_20230706-210932.png](https://github.com/MadeBaruna/paimon-moe/assets/30559735/9bb76649-e107-4e03-8e74-ce78ac185ea6)


I would not call Avast as the most reputable software out there either. Other scans are clean https://www.virustotal.com/gui/url/8045fe2d42eb174d88e678cbe3ec4a85526c2d1cdbcea18c82c3cb4332b5563f/detection

The reference to the URL has lived there since ever https://github.com/MadeBaruna/paimon-moe/blob/a13901524bbc7d791495b707640145696850ab5e/src/app.html#L19

The content would be automatically generated by plausible.io

If anything you should contact [plausible.io](https://plausible.io/contact) or Avast directly.

**Comment by ryanbenson** [comment]
@jogerj 

> I would not call Avast as the most reputable software out there either.
> ...
> Other scans are clean

Avast has a pretty good reputation. It's not perfect, but it's not genuine to say it's not reputable. Probably the thing hurting their reputation the most is their privacy concerns, not their security. https://selabs.uk/reports/home-endpoint-protection-2022-q2/ shows it's ranked pretty high in security.

And other scans are clean, that's why I posted Google's, as they say it's clean too.

> Google is flagging it as safe: https://transparencyreport.google.com/safe-browsing/search

For why it's being flagged, I can't tell you. I posted more information to help because the original issue report didn't have much to go off of. You're right that it could simply be them flagging Plausible.io as a whole.

But like I said, something changed either on a recent release, or on security scanners to start flagging the script, or the domain.

Agreed that the best course is to reach out to Avast and/or Plausible about this. They'd be able to determine the root cause of it being flagged.

**Comment by ryanbenson** [comment]
@RaSan147 Can you confirm this happens still, or if it's fixed?

I just tried it and the Avast alerts no longer appear. I didn't whitelist/exclude anything on my end. Things may have cleared up with the false positive report.

**Comment by RaSan147** [comment]
I'll re check by removing from whitelist...

**Comment by ryanbenson** [comment]
@RaSan147 thanks for checking! It should be resolved. Avast responded and verified on their end too it should be good now

> The reported URL was checked by Avast virus specialists and based on the findings the detection was removed. The website is now marked as clean in the Avast virus database. This change may take up to 1 hour to take full effect. Please accept my apology for the inconvenience caused.

> 
> If the detection persists after 1 hour, please [update the Avast virus database](https://support.avast.com/article/update-antivirus/)

**Comment by RaSan147** [comment]
Fixed, closing issue
